Lazy
Anastasia-Nikitina/Homework3Semester pull request #5
Opened 2022-02-05 12:06 UTC by Anastasia-Nikitina

2022-02-19 16:09 UTC, yurii-litvinov requested changes
В целом ок, но надо поправить предупреждения и стайлгайд

2022-02-19 16:09 UTC, yurii-litvinov commented on Lazy/Lazy/ILazy.cs
> +    /// <returns></returns>
Пустые тэги в комментариях не нужны, надо либо всё-таки написать сюда что-то, либо удалить эту часть вовсе

2022-02-19 16:09 UTC, yurii-litvinov commented on Lazy/Lazy/LazyFactory.cs
> +    public static ILazy<T> CreateSingleThreadedLazy<T>(Func<T>? supplier)
Не надо supplier-у быть nullable

2022-02-19 16:09 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadedLazy.cs
> +    private volatile bool _isCalculated;
Не стоит использовать подчёркивания для обозначения полей

2022-02-19 16:09 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadedLazy.cs
> +        => _supplier = supplier ?? throw new ArgumentNullException();
GitHub Actions недоволен, это предупреждение компилятора, а предупреждения компилятора надо править

2022-02-19 16:09 UTC, yurii-litvinov commented on Lazy/LazyTests/Tests.cs
> +        var function = LazyFactory.CreateSingleThreadedLazy<int>(()=> a);
```suggestion
        var function = LazyFactory.CreateSingleThreadedLazy<int>(() => a);
```

2022-02-19 16:09 UTC, yurii-litvinov commented on Lazy/LazyTests/Tests.cs
> +            Assert.IsTrue(function.Get() == 1);
```suggestion
            Assert.AreEqual(1, function.Get());
```
Так оно будет более понятно ругаться

2022-02-19 16:09 UTC, yurii-litvinov commented on Lazy/LazyTests/Tests.cs
> +            threads[i] = new Thread(() => Interlocked.Add( ref result, function.Get()));
```suggestion
            threads[i] = new Thread(() => Interlocked.Add(ref result, function.Get()));
```

2022-02-28 10:18 UTC, Anastasia-Nikitina commented on Lazy/Lazy/MultiThreadedLazy.cs
> +    private volatile bool _isCalculated;
а как лучше? просто с маленькой буквы и без подчеркивания? или с большой?

2022-03-07 10:25 UTC, yurii-litvinov requested changes

2022-03-07 10:25 UTC, yurii-litvinov commented on Lazy/Lazy/ILazy.cs
> +    public T? Get();
Кстати, именно `T?`, не `T`? Оно может быть null?

2022-03-07 10:25 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadedLazy.cs
> +    private volatile bool _isCalculated;
Поля с маленькой, свойства с большой. Но с подчёркиванием тоже иногда пишут, так что это не критично.

2022-03-07 10:25 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadedLazy.cs
> +        _supplier = supplier ?? throw new ArgumentNullException();
Есть [ArgumentNullException.ThrowIfNull](https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull), удобнее.

2022-03-07 10:25 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadedLazy.cs
> +        _supplier = supplier ?? throw new ArgumentNullException();
Тем более что тут, кажется, supplier и так не null, он ведь без вопросика

2022-03-07 10:25 UTC, yurii-litvinov commented on Lazy/LazyTests/Tests.cs
> +        Assert.Throws<ArgumentNullException>(() => LazyFactory.CreateMultiThreadedLazy<int>(null!));
Не, если компилятор ругается на null-ы, то можно этот случай и не тестировать.

2022-03-07 10:25 UTC, yurii-litvinov commented on Lazy/LazyTests/Tests.cs
> +        }
А в чём хитрый план? Чем это отличается от `LazyFactory.CreateSingleThreadedLazy(() => 1);`?

2022-03-07 10:25 UTC, yurii-litvinov commented on Lazy/LazyTests/Tests.cs
> +namespace LazyTests;
На мой вкус лучше namespace в начале файла, первой строкой

2022-03-27 15:13 UTC, merged